# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_compliance_jobs.post import CreateJobRaw
from x_python_sdk.paths._2_compliance_jobs_id.get import GetJobByIdRaw
from x_python_sdk.paths._2_compliance_jobs.get import ListJobsRaw
from x_python_sdk.paths._2_tweets_compliance_stream.get import StreamDataRaw
from x_python_sdk.paths._2_tweets_label_stream.get import StreamTweetsLabelEventsRaw
from x_python_sdk.paths._2_users_compliance_stream.get import StreamUsersDataRaw


class ComplianceApiRaw(
    CreateJobRaw,
    GetJobByIdRaw,
    ListJobsRaw,
    StreamDataRaw,
    StreamTweetsLabelEventsRaw,
    StreamUsersDataRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
