# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_compliance_jobs.post import CreateJob
from x_python_sdk.paths._2_compliance_jobs_id.get import GetJobById
from x_python_sdk.paths._2_compliance_jobs.get import ListJobs
from x_python_sdk.paths._2_tweets_compliance_stream.get import StreamData
from x_python_sdk.paths._2_tweets_label_stream.get import StreamTweetsLabelEvents
from x_python_sdk.paths._2_users_compliance_stream.get import StreamUsersData
from x_python_sdk.apis.tags.compliance_api_raw import ComplianceApiRaw


class ComplianceApi(
    CreateJob,
    GetJobById,
    ListJobs,
    StreamData,
    StreamTweetsLabelEvents,
    StreamUsersData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ComplianceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ComplianceApiRaw(api_client)
