# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_dm_conversations.post import CreateNewDmConversation
from x_python_sdk.paths._2_dm_conversations_with_participant_id_dm_events.get import GetDmEvents
from x_python_sdk.paths._2_dm_conversations_id_dm_events.get import GetDmEvents0
from x_python_sdk.paths._2_dm_events.get import GetRecentDmEvents
from x_python_sdk.paths._2_dm_conversations_dm_conversation_id_messages.post import SendNewMessageToDmConversation
from x_python_sdk.paths._2_dm_conversations_with_participant_id_messages.post import SendNewMessageToUser
from x_python_sdk.apis.tags.direct_messages_api_raw import DirectMessagesApiRaw


class DirectMessagesApi(
    CreateNewDmConversation,
    GetDmEvents,
    GetDmEvents0,
    GetRecentDmEvents,
    SendNewMessageToDmConversation,
    SendNewMessageToUser,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DirectMessagesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DirectMessagesApiRaw(api_client)
