# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_dm_conversations.post import CreateNewDmConversationRaw
from x_python_sdk.paths._2_dm_conversations_with_participant_id_dm_events.get import GetDmEventsRaw
from x_python_sdk.paths._2_dm_conversations_id_dm_events.get import GetDmEvents0Raw
from x_python_sdk.paths._2_dm_events.get import GetRecentDmEventsRaw
from x_python_sdk.paths._2_dm_conversations_dm_conversation_id_messages.post import SendNewMessageToDmConversationRaw
from x_python_sdk.paths._2_dm_conversations_with_participant_id_messages.post import SendNewMessageToUserRaw


class DirectMessagesApiRaw(
    CreateNewDmConversationRaw,
    GetDmEventsRaw,
    GetDmEvents0Raw,
    GetRecentDmEventsRaw,
    SendNewMessageToDmConversationRaw,
    SendNewMessageToUserRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
