# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_openapi_json.get import GetOpenApiSpecRaw


class GeneralApiRaw(
    GetOpenApiSpecRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
