# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_lists_id_members.post import AddMemberRaw
from x_python_sdk.paths._2_lists.post import CreateNewListRaw
from x_python_sdk.paths._2_lists_id.delete import DeleteOwnedListRaw
from x_python_sdk.paths._2_users_id_followed_lists.post import FollowListRaw
from x_python_sdk.paths._2_users_id_followed_lists.get import GetFollowedRaw
from x_python_sdk.paths._2_users_id_list_memberships.get import GetUserMembershipsRaw
from x_python_sdk.paths._2_users_id_owned_lists.get import GetUserOwnedListsRaw
from x_python_sdk.paths._2_users_id_pinned_lists.get import GetUserPinnedListsRaw
from x_python_sdk.paths._2_lists_id.get import LookupByListIdRaw
from x_python_sdk.paths._2_users_id_pinned_lists.post import PinListRaw
from x_python_sdk.paths._2_lists_id_members_user_id.delete import RemoveMemberRaw
from x_python_sdk.paths._2_users_id_followed_lists_list_id.delete import UnfollowListRaw
from x_python_sdk.paths._2_users_id_pinned_lists_list_id.delete import UnpinListRaw
from x_python_sdk.paths._2_lists_id.put import UpdateOwnedListRaw


class ListsApiRaw(
    AddMemberRaw,
    CreateNewListRaw,
    DeleteOwnedListRaw,
    FollowListRaw,
    GetFollowedRaw,
    GetUserMembershipsRaw,
    GetUserOwnedListsRaw,
    GetUserPinnedListsRaw,
    LookupByListIdRaw,
    PinListRaw,
    RemoveMemberRaw,
    UnfollowListRaw,
    UnpinListRaw,
    UpdateOwnedListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
