# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_spaces_search.get import FindMatchingSpacesRaw
from x_python_sdk.paths._2_spaces_id_buyers.get import GetBuyersListRaw
from x_python_sdk.paths._2_spaces_id_tweets.get import GetTweetsRaw
from x_python_sdk.paths._2_spaces_by_creator_ids.get import LookupByCreatorIdsRaw
from x_python_sdk.paths._2_spaces_id.get import LookupSpaceByIdRaw
from x_python_sdk.paths._2_spaces.get import LookupSpaceIdsRaw


class SpacesApiRaw(
    FindMatchingSpacesRaw,
    GetBuyersListRaw,
    GetTweetsRaw,
    LookupByCreatorIdsRaw,
    LookupSpaceByIdRaw,
    LookupSpaceIdsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
