# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_spaces_search.get import FindMatchingSpaces
from x_python_sdk.paths._2_spaces_id_buyers.get import GetBuyersList
from x_python_sdk.paths._2_spaces_id_tweets.get import GetTweets
from x_python_sdk.paths._2_spaces_by_creator_ids.get import LookupByCreatorIds
from x_python_sdk.paths._2_spaces_id.get import LookupSpaceById
from x_python_sdk.paths._2_spaces.get import LookupSpaceIds
from x_python_sdk.apis.tags.spaces_api_raw import SpacesApiRaw


class SpacesApi(
    FindMatchingSpaces,
    GetBuyersList,
    GetTweets,
    LookupByCreatorIds,
    LookupSpaceById,
    LookupSpaceIds,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SpacesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SpacesApiRaw(api_client)
