# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_tweets_search_stream_rules.post import AddOrDeleteRules
from x_python_sdk.paths._2_tweets.post import CreateTweet
from x_python_sdk.paths._2_tweets_id.delete import DeleteById
from x_python_sdk.paths._2_spaces_id_buyers.get import GetBuyersList
from x_python_sdk.paths._2_tweets_search_stream.get import GetFilteredStream
from x_python_sdk.paths._2_tweets_firehose_stream.get import GetFirehoseStream
from x_python_sdk.paths._2_users_id_liked_tweets.get import GetLikedTweets
from x_python_sdk.paths._2_users_id_mentions.get import GetMentionsById
from x_python_sdk.paths._2_tweets_id_quote_tweets.get import GetQuoteTweets
from x_python_sdk.paths._2_tweets_counts_recent.get import GetRecentTweetCounts
from x_python_sdk.paths._2_tweets_search_recent.get import GetRecentTweets
from x_python_sdk.paths._2_tweets_counts_all.get import GetTweetCounts
from x_python_sdk.paths._2_spaces_id_tweets.get import GetTweets
from x_python_sdk.paths._2_users_id_timelines_reverse_chronological.get import GetUserHomeTimeline
from x_python_sdk.paths._2_tweets_tweet_id_hidden.put import HideReply
from x_python_sdk.paths._2_users_id_likes.post import LikeTweet
from x_python_sdk.paths._2_lists_id_tweets.get import ListByListId
from x_python_sdk.paths._2_users_id_tweets.get import ListByUserId
from x_python_sdk.paths._2_tweets_id.get import LookupById
from x_python_sdk.paths._2_tweets.get import LookupByTweetIds
from x_python_sdk.paths._2_users_id_retweets.post import RetweetTweetById
from x_python_sdk.paths._2_tweets_search_all.get import SearchAll
from x_python_sdk.paths._2_tweets_search_stream_rules.get import SearchStreamRules
from x_python_sdk.paths._2_tweets_sample_stream.get import StreamSample
from x_python_sdk.paths._2_tweets_sample10_stream.get import StreamSample10
from x_python_sdk.paths._2_users_id_likes_tweet_id.delete import UnlikeTweetById
from x_python_sdk.paths._2_users_id_retweets_source_tweet_id.delete import UnretweetById
from x_python_sdk.apis.tags.tweets_api_raw import TweetsApiRaw


class TweetsApi(
    AddOrDeleteRules,
    CreateTweet,
    DeleteById,
    GetBuyersList,
    GetFilteredStream,
    GetFirehoseStream,
    GetLikedTweets,
    GetMentionsById,
    GetQuoteTweets,
    GetRecentTweetCounts,
    GetRecentTweets,
    GetTweetCounts,
    GetTweets,
    GetUserHomeTimeline,
    HideReply,
    LikeTweet,
    ListByListId,
    ListByUserId,
    LookupById,
    LookupByTweetIds,
    RetweetTweetById,
    SearchAll,
    SearchStreamRules,
    StreamSample,
    StreamSample10,
    UnlikeTweetById,
    UnretweetById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TweetsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TweetsApiRaw(api_client)
