# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_users_id_blocking.post import BlockUserById
from x_python_sdk.paths._2_users_id_following.post import FollowUser
from x_python_sdk.paths._2_users_id_blocking.get import GetBlockedUsers
from x_python_sdk.paths._2_users_id_followers.get import GetFollowersById
from x_python_sdk.paths._2_lists_id_followers.get import GetFollowersByListId
from x_python_sdk.paths._2_users_id_following.get import GetFollowingUsers
from x_python_sdk.paths._2_lists_id_members.get import GetMembersByListId
from x_python_sdk.paths._2_users_id_muting.get import GetMutedUsersById
from x_python_sdk.paths._2_tweets_id_retweeted_by.get import GetRetweetedByTweetIdUsers
from x_python_sdk.paths._2_tweets_id_liking_users.get import ListLikingUsers
from x_python_sdk.paths._2_users_id.get import LookupById
from x_python_sdk.paths._2_users.get import LookupByIds
from x_python_sdk.paths._2_users_by_username_username.get import LookupByUsername
from x_python_sdk.paths._2_users_by.get import LookupByUsernames
from x_python_sdk.paths._2_users_me.get import LookupMe
from x_python_sdk.paths._2_users_id_muting.post import MuteUserById
from x_python_sdk.paths._2_users_source_user_id_blocking_target_user_id.delete import UnblockUserById
from x_python_sdk.paths._2_users_source_user_id_following_target_user_id.delete import UnfollowUser
from x_python_sdk.paths._2_users_source_user_id_muting_target_user_id.delete import UnmuteByUserId
from x_python_sdk.apis.tags.users_api_raw import UsersApiRaw


class UsersApi(
    BlockUserById,
    FollowUser,
    GetBlockedUsers,
    GetFollowersById,
    GetFollowersByListId,
    GetFollowingUsers,
    GetMembersByListId,
    GetMutedUsersById,
    GetRetweetedByTweetIdUsers,
    ListLikingUsers,
    LookupById,
    LookupByIds,
    LookupByUsername,
    LookupByUsernames,
    LookupMe,
    MuteUserById,
    UnblockUserById,
    UnfollowUser,
    UnmuteByUserId,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
