# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from x_python_sdk.paths._2_users_id_blocking.post import BlockUserByIdRaw
from x_python_sdk.paths._2_users_id_following.post import FollowUserRaw
from x_python_sdk.paths._2_users_id_blocking.get import GetBlockedUsersRaw
from x_python_sdk.paths._2_users_id_followers.get import GetFollowersByIdRaw
from x_python_sdk.paths._2_lists_id_followers.get import GetFollowersByListIdRaw
from x_python_sdk.paths._2_users_id_following.get import GetFollowingUsersRaw
from x_python_sdk.paths._2_lists_id_members.get import GetMembersByListIdRaw
from x_python_sdk.paths._2_users_id_muting.get import GetMutedUsersByIdRaw
from x_python_sdk.paths._2_tweets_id_retweeted_by.get import GetRetweetedByTweetIdUsersRaw
from x_python_sdk.paths._2_tweets_id_liking_users.get import ListLikingUsersRaw
from x_python_sdk.paths._2_users_id.get import LookupByIdRaw
from x_python_sdk.paths._2_users.get import LookupByIdsRaw
from x_python_sdk.paths._2_users_by_username_username.get import LookupByUsernameRaw
from x_python_sdk.paths._2_users_by.get import LookupByUsernamesRaw
from x_python_sdk.paths._2_users_me.get import LookupMeRaw
from x_python_sdk.paths._2_users_id_muting.post import MuteUserByIdRaw
from x_python_sdk.paths._2_users_source_user_id_blocking_target_user_id.delete import UnblockUserByIdRaw
from x_python_sdk.paths._2_users_source_user_id_following_target_user_id.delete import UnfollowUserRaw
from x_python_sdk.paths._2_users_source_user_id_muting_target_user_id.delete import UnmuteByUserIdRaw


class UsersApiRaw(
    BlockUserByIdRaw,
    FollowUserRaw,
    GetBlockedUsersRaw,
    GetFollowersByIdRaw,
    GetFollowersByListIdRaw,
    GetFollowingUsersRaw,
    GetMembersByListIdRaw,
    GetMutedUsersByIdRaw,
    GetRetweetedByTweetIdUsersRaw,
    ListLikingUsersRaw,
    LookupByIdRaw,
    LookupByIdsRaw,
    LookupByUsernameRaw,
    LookupByUsernamesRaw,
    LookupMeRaw,
    MuteUserByIdRaw,
    UnblockUserByIdRaw,
    UnfollowUserRaw,
    UnmuteByUserIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
