# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from x_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    _2_COMPLIANCE_JOBS = "/2/compliance/jobs"
    _2_COMPLIANCE_JOBS_ID = "/2/compliance/jobs/{id}"
    _2_DM_CONVERSATIONS = "/2/dm_conversations"
    _2_DM_CONVERSATIONS_WITH_PARTICIPANT_ID_DM_EVENTS = "/2/dm_conversations/with/{participant_id}/dm_events"
    _2_DM_CONVERSATIONS_WITH_PARTICIPANT_ID_MESSAGES = "/2/dm_conversations/with/{participant_id}/messages"
    _2_DM_CONVERSATIONS_DM_CONVERSATION_ID_MESSAGES = "/2/dm_conversations/{dm_conversation_id}/messages"
    _2_DM_CONVERSATIONS_ID_DM_EVENTS = "/2/dm_conversations/{id}/dm_events"
    _2_DM_EVENTS = "/2/dm_events"
    _2_LISTS = "/2/lists"
    _2_LISTS_ID = "/2/lists/{id}"
    _2_LISTS_ID_FOLLOWERS = "/2/lists/{id}/followers"
    _2_LISTS_ID_MEMBERS = "/2/lists/{id}/members"
    _2_LISTS_ID_MEMBERS_USER_ID = "/2/lists/{id}/members/{user_id}"
    _2_LISTS_ID_TWEETS = "/2/lists/{id}/tweets"
    _2_OPENAPI_JSON = "/2/openapi.json"
    _2_SPACES = "/2/spaces"
    _2_SPACES_BY_CREATOR_IDS = "/2/spaces/by/creator_ids"
    _2_SPACES_SEARCH = "/2/spaces/search"
    _2_SPACES_ID = "/2/spaces/{id}"
    _2_SPACES_ID_BUYERS = "/2/spaces/{id}/buyers"
    _2_SPACES_ID_TWEETS = "/2/spaces/{id}/tweets"
    _2_TWEETS = "/2/tweets"
    _2_TWEETS_COMPLIANCE_STREAM = "/2/tweets/compliance/stream"
    _2_TWEETS_COUNTS_ALL = "/2/tweets/counts/all"
    _2_TWEETS_COUNTS_RECENT = "/2/tweets/counts/recent"
    _2_TWEETS_FIREHOSE_STREAM = "/2/tweets/firehose/stream"
    _2_TWEETS_LABEL_STREAM = "/2/tweets/label/stream"
    _2_TWEETS_SAMPLE_STREAM = "/2/tweets/sample/stream"
    _2_TWEETS_SAMPLE10_STREAM = "/2/tweets/sample10/stream"
    _2_TWEETS_SEARCH_ALL = "/2/tweets/search/all"
    _2_TWEETS_SEARCH_RECENT = "/2/tweets/search/recent"
    _2_TWEETS_SEARCH_STREAM = "/2/tweets/search/stream"
    _2_TWEETS_SEARCH_STREAM_RULES = "/2/tweets/search/stream/rules"
    _2_TWEETS_ID = "/2/tweets/{id}"
    _2_TWEETS_ID_LIKING_USERS = "/2/tweets/{id}/liking_users"
    _2_TWEETS_ID_QUOTE_TWEETS = "/2/tweets/{id}/quote_tweets"
    _2_TWEETS_ID_RETWEETED_BY = "/2/tweets/{id}/retweeted_by"
    _2_TWEETS_TWEET_ID_HIDDEN = "/2/tweets/{tweet_id}/hidden"
    _2_USERS = "/2/users"
    _2_USERS_BY = "/2/users/by"
    _2_USERS_BY_USERNAME_USERNAME = "/2/users/by/username/{username}"
    _2_USERS_COMPLIANCE_STREAM = "/2/users/compliance/stream"
    _2_USERS_ME = "/2/users/me"
    _2_USERS_ID = "/2/users/{id}"
    _2_USERS_ID_BLOCKING = "/2/users/{id}/blocking"
    _2_USERS_ID_BOOKMARKS = "/2/users/{id}/bookmarks"
    _2_USERS_ID_BOOKMARKS_TWEET_ID = "/2/users/{id}/bookmarks/{tweet_id}"
    _2_USERS_ID_FOLLOWED_LISTS = "/2/users/{id}/followed_lists"
    _2_USERS_ID_FOLLOWED_LISTS_LIST_ID = "/2/users/{id}/followed_lists/{list_id}"
    _2_USERS_ID_FOLLOWERS = "/2/users/{id}/followers"
    _2_USERS_ID_FOLLOWING = "/2/users/{id}/following"
    _2_USERS_ID_LIKED_TWEETS = "/2/users/{id}/liked_tweets"
    _2_USERS_ID_LIKES = "/2/users/{id}/likes"
    _2_USERS_ID_LIKES_TWEET_ID = "/2/users/{id}/likes/{tweet_id}"
    _2_USERS_ID_LIST_MEMBERSHIPS = "/2/users/{id}/list_memberships"
    _2_USERS_ID_MENTIONS = "/2/users/{id}/mentions"
    _2_USERS_ID_MUTING = "/2/users/{id}/muting"
    _2_USERS_ID_OWNED_LISTS = "/2/users/{id}/owned_lists"
    _2_USERS_ID_PINNED_LISTS = "/2/users/{id}/pinned_lists"
    _2_USERS_ID_PINNED_LISTS_LIST_ID = "/2/users/{id}/pinned_lists/{list_id}"
    _2_USERS_ID_RETWEETS = "/2/users/{id}/retweets"
    _2_USERS_ID_RETWEETS_SOURCE_TWEET_ID = "/2/users/{id}/retweets/{source_tweet_id}"
    _2_USERS_ID_TIMELINES_REVERSE_CHRONOLOGICAL = "/2/users/{id}/timelines/reverse_chronological"
    _2_USERS_ID_TWEETS = "/2/users/{id}/tweets"
    _2_USERS_SOURCE_USER_ID_BLOCKING_TARGET_USER_ID = "/2/users/{source_user_id}/blocking/{target_user_id}"
    _2_USERS_SOURCE_USER_ID_FOLLOWING_TARGET_USER_ID = "/2/users/{source_user_id}/following/{target_user_id}"
    _2_USERS_SOURCE_USER_ID_MUTING_TARGET_USER_ID = "/2/users/{source_user_id}/muting/{target_user_id}"
