# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from x_python_sdk import schemas  # noqa: F401


class AddRulesRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A request to add a user-specified stream filtering rule.
    """


    class MetaOapg:
        required = {
            "add",
        }
        
        class properties:
            
            
            class add(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['RuleNoId']:
                        return RuleNoId
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['RuleNoId'], typing.List['RuleNoId']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'add':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'RuleNoId':
                    return super().__getitem__(i)
            __annotations__ = {
                "add": add,
            }
    
    add: MetaOapg.properties.add
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["add"]) -> MetaOapg.properties.add: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["add", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["add"]) -> MetaOapg.properties.add: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["add", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        add: typing.Union[MetaOapg.properties.add, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AddRulesRequest':
        return super().__new__(
            cls,
            *args,
            add=add,
            _configuration=_configuration,
            **kwargs,
        )

from x_python_sdk.model.rule_no_id import RuleNoId
