# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from x_python_sdk import schemas  # noqa: F401


class ContextAnnotation(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Annotation inferred from the Tweet text.
    """


    class MetaOapg:
        required = {
            "domain",
            "entity",
        }
        
        class properties:
        
            @staticmethod
            def domain() -> typing.Type['ContextAnnotationDomainFields']:
                return ContextAnnotationDomainFields
        
            @staticmethod
            def entity() -> typing.Type['ContextAnnotationEntityFields']:
                return ContextAnnotationEntityFields
            __annotations__ = {
                "domain": domain,
                "entity": entity,
            }
    
    domain: 'ContextAnnotationDomainFields'
    entity: 'ContextAnnotationEntityFields'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domain"]) -> 'ContextAnnotationDomainFields': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["entity"]) -> 'ContextAnnotationEntityFields': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["domain", "entity", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domain"]) -> 'ContextAnnotationDomainFields': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["entity"]) -> 'ContextAnnotationEntityFields': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["domain", "entity", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        domain: 'ContextAnnotationDomainFields',
        entity: 'ContextAnnotationEntityFields',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ContextAnnotation':
        return super().__new__(
            cls,
            *args,
            domain=domain,
            entity=entity,
            _configuration=_configuration,
            **kwargs,
        )

from x_python_sdk.model.context_annotation_domain_fields import ContextAnnotationDomainFields
from x_python_sdk.model.context_annotation_entity_fields import ContextAnnotationEntityFields
