# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from x_python_sdk import schemas  # noqa: F401


class DisallowedResourceProblem(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A problem that indicates that the resource requested violates the precepts of this API.
    """


    class MetaOapg:
        
        @staticmethod
        def discriminator():
            return {
                'type': {
                    'about:blank': GenericProblem,
                    'https://api.twitter.com/2/problems/client-disconnected': ClientDisconnectedProblem,
                    'https://api.twitter.com/2/problems/client-forbidden': ClientForbiddenProblem,
                    'https://api.twitter.com/2/problems/conflict': ConflictProblem,
                    'https://api.twitter.com/2/problems/disallowed-resource': DisallowedResourceProblem,
                    'https://api.twitter.com/2/problems/duplicate-rules': DuplicateRuleProblem,
                    'https://api.twitter.com/2/problems/invalid-request': InvalidRequestProblem,
                    'https://api.twitter.com/2/problems/invalid-rules': InvalidRuleProblem,
                    'https://api.twitter.com/2/problems/noncompliant-rules': NonCompliantRulesProblem,
                    'https://api.twitter.com/2/problems/not-authorized-for-field': FieldUnauthorizedProblem,
                    'https://api.twitter.com/2/problems/not-authorized-for-resource': ResourceUnauthorizedProblem,
                    'https://api.twitter.com/2/problems/oauth1-permissions': Oauth1PermissionsProblem,
                    'https://api.twitter.com/2/problems/operational-disconnect': OperationalDisconnectProblem,
                    'https://api.twitter.com/2/problems/resource-not-found': ResourceNotFoundProblem,
                    'https://api.twitter.com/2/problems/resource-unavailable': ResourceUnavailableProblem,
                    'https://api.twitter.com/2/problems/rule-cap': RulesCapProblem,
                    'https://api.twitter.com/2/problems/streaming-connection': ConnectionExceptionProblem,
                    'https://api.twitter.com/2/problems/unsupported-authentication': UnsupportedAuthenticationProblem,
                    'https://api.twitter.com/2/problems/usage-capped': UsageCapExceededProblem,
                }
            }
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                required = {
                    "resource_type",
                    "resource_id",
                    "section",
                }
                
                class properties:
                    resource_id = schemas.StrSchema
                    
                    
                    class resource_type(
                        schemas.EnumBase,
                        schemas.StrSchema
                    ):
                        
                        @schemas.classproperty
                        def USER(cls):
                            return cls("user")
                        
                        @schemas.classproperty
                        def TWEET(cls):
                            return cls("tweet")
                        
                        @schemas.classproperty
                        def MEDIA(cls):
                            return cls("media")
                        
                        @schemas.classproperty
                        def LIST(cls):
                            return cls("list")
                        
                        @schemas.classproperty
                        def SPACE(cls):
                            return cls("space")
                    
                    
                    class section(
                        schemas.EnumBase,
                        schemas.StrSchema
                    ):
                        
                        @schemas.classproperty
                        def DATA(cls):
                            return cls("data")
                        
                        @schemas.classproperty
                        def INCLUDES(cls):
                            return cls("includes")
                    __annotations__ = {
                        "resource_id": resource_id,
                        "resource_type": resource_type,
                        "section": section,
                    }
            
            resource_type: MetaOapg.properties.resource_type
            resource_id: MetaOapg.properties.resource_id
            section: MetaOapg.properties.section
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["resource_id"]) -> MetaOapg.properties.resource_id: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["resource_type"]) -> MetaOapg.properties.resource_type: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["section"]) -> MetaOapg.properties.section: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["resource_id", "resource_type", "section", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["resource_id"]) -> MetaOapg.properties.resource_id: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["resource_type"]) -> MetaOapg.properties.resource_type: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["section"]) -> MetaOapg.properties.section: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["resource_id", "resource_type", "section", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                resource_type: typing.Union[MetaOapg.properties.resource_type, str, ],
                resource_id: typing.Union[MetaOapg.properties.resource_id, str, ],
                section: typing.Union[MetaOapg.properties.section, str, ],
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *args,
                    resource_type=resource_type,
                    resource_id=resource_id,
                    section=section,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                Problem,
                cls.all_of_1,
            ]


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DisallowedResourceProblem':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from x_python_sdk.model.client_disconnected_problem import ClientDisconnectedProblem
from x_python_sdk.model.client_forbidden_problem import ClientForbiddenProblem
from x_python_sdk.model.conflict_problem import ConflictProblem
from x_python_sdk.model.connection_exception_problem import ConnectionExceptionProblem
from x_python_sdk.model.disallowed_resource_problem import DisallowedResourceProblem
from x_python_sdk.model.duplicate_rule_problem import DuplicateRuleProblem
from x_python_sdk.model.field_unauthorized_problem import FieldUnauthorizedProblem
from x_python_sdk.model.generic_problem import GenericProblem
from x_python_sdk.model.invalid_request_problem import InvalidRequestProblem
from x_python_sdk.model.invalid_rule_problem import InvalidRuleProblem
from x_python_sdk.model.non_compliant_rules_problem import NonCompliantRulesProblem
from x_python_sdk.model.oauth1_permissions_problem import Oauth1PermissionsProblem
from x_python_sdk.model.operational_disconnect_problem import OperationalDisconnectProblem
from x_python_sdk.model.problem import Problem
from x_python_sdk.model.resource_not_found_problem import ResourceNotFoundProblem
from x_python_sdk.model.resource_unauthorized_problem import ResourceUnauthorizedProblem
from x_python_sdk.model.resource_unavailable_problem import ResourceUnavailableProblem
from x_python_sdk.model.rules_cap_problem import RulesCapProblem
from x_python_sdk.model.unsupported_authentication_problem import UnsupportedAuthenticationProblem
from x_python_sdk.model.usage_cap_exceeded_problem import UsageCapExceededProblem
