# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from x_python_sdk import schemas  # noqa: F401


class DmEventReferencedTweets(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    A list of Tweets this DM refers to.
    """


    class MetaOapg:
        min_items = 1
        
        @staticmethod
        def items() -> typing.Type['DmEventReferencedTweetsItem']:
            return DmEventReferencedTweetsItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['DmEventReferencedTweetsItem'], typing.List['DmEventReferencedTweetsItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'DmEventReferencedTweets':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'DmEventReferencedTweetsItem':
        return super().__getitem__(i)

from x_python_sdk.model.dm_event_referenced_tweets_item import DmEventReferencedTweetsItem
