# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from x_python_sdk import schemas  # noqa: F401


class PollOption(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Describes a choice in a Poll object.
    """


    class MetaOapg:
        required = {
            "votes",
            "label",
            "position",
        }
        
        class properties:
        
            @staticmethod
            def label() -> typing.Type['PollOptionLabel']:
                return PollOptionLabel
            position = schemas.IntSchema
            votes = schemas.IntSchema
            __annotations__ = {
                "label": label,
                "position": position,
                "votes": votes,
            }
    
    votes: MetaOapg.properties.votes
    label: 'PollOptionLabel'
    position: MetaOapg.properties.position
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["label"]) -> 'PollOptionLabel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["position"]) -> MetaOapg.properties.position: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["votes"]) -> MetaOapg.properties.votes: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["label", "position", "votes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["label"]) -> 'PollOptionLabel': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["position"]) -> MetaOapg.properties.position: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["votes"]) -> MetaOapg.properties.votes: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["label", "position", "votes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        votes: typing.Union[MetaOapg.properties.votes, decimal.Decimal, int, ],
        label: 'PollOptionLabel',
        position: typing.Union[MetaOapg.properties.position, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PollOption':
        return super().__new__(
            cls,
            *args,
            votes=votes,
            label=label,
            position=position,
            _configuration=_configuration,
            **kwargs,
        )

from x_python_sdk.model.poll_option_label import PollOptionLabel
