# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from x_python_sdk import schemas  # noqa: F401


class TweetNotice(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "event_type",
            "application",
            "event_at",
            "tweet",
        }
        
        class properties:
            application = schemas.StrSchema
            event_at = schemas.DateTimeSchema
            event_type = schemas.StrSchema
        
            @staticmethod
            def tweet() -> typing.Type['TweetNoticeTweet']:
                return TweetNoticeTweet
            details = schemas.StrSchema
            extended_details_url = schemas.StrSchema
            label_title = schemas.StrSchema
            __annotations__ = {
                "application": application,
                "event_at": event_at,
                "event_type": event_type,
                "tweet": tweet,
                "details": details,
                "extended_details_url": extended_details_url,
                "label_title": label_title,
            }
    
    event_type: MetaOapg.properties.event_type
    application: MetaOapg.properties.application
    event_at: MetaOapg.properties.event_at
    tweet: 'TweetNoticeTweet'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["application"]) -> MetaOapg.properties.application: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["event_at"]) -> MetaOapg.properties.event_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["event_type"]) -> MetaOapg.properties.event_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tweet"]) -> 'TweetNoticeTweet': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["details"]) -> MetaOapg.properties.details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["extended_details_url"]) -> MetaOapg.properties.extended_details_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["label_title"]) -> MetaOapg.properties.label_title: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["application", "event_at", "event_type", "tweet", "details", "extended_details_url", "label_title", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["application"]) -> MetaOapg.properties.application: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["event_at"]) -> MetaOapg.properties.event_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["event_type"]) -> MetaOapg.properties.event_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tweet"]) -> 'TweetNoticeTweet': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["details"]) -> typing.Union[MetaOapg.properties.details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["extended_details_url"]) -> typing.Union[MetaOapg.properties.extended_details_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["label_title"]) -> typing.Union[MetaOapg.properties.label_title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["application", "event_at", "event_type", "tweet", "details", "extended_details_url", "label_title", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        event_type: typing.Union[MetaOapg.properties.event_type, str, ],
        application: typing.Union[MetaOapg.properties.application, str, ],
        event_at: typing.Union[MetaOapg.properties.event_at, str, datetime, ],
        tweet: 'TweetNoticeTweet',
        details: typing.Union[MetaOapg.properties.details, str, schemas.Unset] = schemas.unset,
        extended_details_url: typing.Union[MetaOapg.properties.extended_details_url, str, schemas.Unset] = schemas.unset,
        label_title: typing.Union[MetaOapg.properties.label_title, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TweetNotice':
        return super().__new__(
            cls,
            *args,
            event_type=event_type,
            application=application,
            event_at=event_at,
            tweet=tweet,
            details=details,
            extended_details_url=extended_details_url,
            label_title=label_title,
            _configuration=_configuration,
            **kwargs,
        )

from x_python_sdk.model.tweet_notice_tweet import TweetNoticeTweet
