# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from x_python_sdk import schemas  # noqa: F401


class TweetAttachments(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Specifies the type of attachments (if any) present in this Tweet.
    """


    class MetaOapg:
        
        class properties:
            
            
            class media_keys(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['MediaKey']:
                        return MediaKey
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['MediaKey'], typing.List['MediaKey']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'media_keys':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'MediaKey':
                    return super().__getitem__(i)
            
            
            class poll_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PollId']:
                        return PollId
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['PollId'], typing.List['PollId']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'poll_ids':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PollId':
                    return super().__getitem__(i)
            __annotations__ = {
                "media_keys": media_keys,
                "poll_ids": poll_ids,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["media_keys"]) -> MetaOapg.properties.media_keys: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["poll_ids"]) -> MetaOapg.properties.poll_ids: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["media_keys", "poll_ids", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["media_keys"]) -> typing.Union[MetaOapg.properties.media_keys, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["poll_ids"]) -> typing.Union[MetaOapg.properties.poll_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["media_keys", "poll_ids", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        media_keys: typing.Union[MetaOapg.properties.media_keys, list, tuple, schemas.Unset] = schemas.unset,
        poll_ids: typing.Union[MetaOapg.properties.poll_ids, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TweetAttachments':
        return super().__new__(
            cls,
            *args,
            media_keys=media_keys,
            poll_ids=poll_ids,
            _configuration=_configuration,
            **kwargs,
        )

from x_python_sdk.model.media_key import MediaKey
from x_python_sdk.model.poll_id import PollId
