# coding: utf-8

"""
    Twitter API v2

    Twitter API v2 available endpoints

    The version of the OpenAPI document: 2.62
    Created by: https://developer.twitter.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from x_python_sdk import schemas  # noqa: F401


class UserScrubGeoSchema(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "scrub_geo",
        }
        
        class properties:
        
            @staticmethod
            def scrub_geo() -> typing.Type['UserScrubGeoObjectSchema']:
                return UserScrubGeoObjectSchema
            __annotations__ = {
                "scrub_geo": scrub_geo,
            }
    
    scrub_geo: 'UserScrubGeoObjectSchema'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scrub_geo"]) -> 'UserScrubGeoObjectSchema': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["scrub_geo", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scrub_geo"]) -> 'UserScrubGeoObjectSchema': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["scrub_geo", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        scrub_geo: 'UserScrubGeoObjectSchema',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UserScrubGeoSchema':
        return super().__new__(
            cls,
            *args,
            scrub_geo=scrub_geo,
            _configuration=_configuration,
            **kwargs,
        )

from x_python_sdk.model.user_scrub_geo_object_schema import UserScrubGeoObjectSchema
